INSERT INTO union_status(name) VALUES ('United Actors of America');
INSERT INTO union_status(name) VALUES ('National Actors Union');
INSERT INTO age_increment(ages) VALUES ('18-22');
INSERT INTO age_increment(ages) VALUES ('23-27');
INSERT INTO age_increment(ages) VALUES ('28-32');
INSERT INTO age_increment(ages) VALUES ('33-37');
INSERT INTO age_increment(ages) VALUES ('38-42');
INSERT INTO age_increment(ages) VALUES ('43-47');
INSERT INTO age_increment(ages) VALUES ('48-52');
INSERT INTO age_increment(ages) VALUES ('53-57');
INSERT INTO age_increment(ages) VALUES ('58-62');
INSERT INTO age_increment(ages) VALUES ('62+');